method: random
# grid, random, bayesから選択
#bayesの場合, metricを記述
metric:
  name: test_acc
  goal: minimize
# goal:Maximize, Minimize, Targetから選択
parameters:
  batch_size:
    values: [32, 128, 256]
  epochs:
    values: [20, 60, 100]
  learning_rate:
    values: [0.001, 0.01, 0.05]
  n_hidden1:
    values: [32, 128, 256]
  n_hidden2:
    values: [32, 128, 256]
  optimizer:
    values: ["SDG", "Adam"]
  Net:
    values: ["Net1", "Net2"]
    #distribution: int_uniform
      #max: 512
      #min: 64