method: grid
# grid, random, bayesから選択
#bayesの場合, metricを記述
metric:
  name: test_acc
  goal: minimize
# goal:Maximize, Minimize, Targetから選択
parameters:
  optimizer:
    values: ["SDG", "SDG_momentum", "Adam"]
  Net:
    values: ["CNN_v1", "CNN_v2", "CNN_v3", "CNN_v4"]